# Generated by Django 4.1 on 2022-09-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email_origem',
            field=models.CharField(default='(ERR Sem email de origem)', max_length=255),
        ),
        migrations.AlterField(
            model_name='emails',
            name='nome',
            field=models.CharField(default='(ERR Sem nome)', max_length=255),
        ),
        migrations.AlterField(
            model_name='emails',
            name='texto',
            field=models.TextField(default='(ERR Sem texto)'),
        ),
    ]
